#from Infrastructure.repositories.configuration_mongodb import ConfigurationsMongoDBRepository
from Infrastructure.repositories.isps_source_mongodb import IPSourceMongoDBRepository
from Infrastructure.repositories.stocks_dict import StocksDictRepository
from Infrastructure.repositories.ips_source import IPSourceDictRepository
from Infrastructure.repositories.stocks_mongodb import StocksMongoDBRepository
